GDSC SKHU Web - 김신아
GDSC-SKHU/GDSC-Web-Assignment-03 pull request #12
Opened 2022-11-16 12:21 UTC by sinamong0620

## Description

- 컴포넌트를 이용하여 맛집 소개 페이지 제작

## Important content

- 컴포넌트
- styled-component를 이용한 css 작성

## Question

- 궁금한 점 보다는.. 사과의 말씀 드립니다..저번에 슬희님께서 태그 이름 지을 때 한번 읽어보면 좋을 글 추천해주셨는데 그걸 읽고 했어야 했는데 너무 바빠서 그렇게 하지 못했어요 ㅠㅠ 다음번에는 그렇게 하겠습니다 ㅠㅠ 

## Reference

딱히 없습니다!

## 과제 실행 사진
<img width="1300" alt="run screen" src="https://user-images.githubusercontent.com/114804676/202178794-cb3ee5ce-41ec-4705-8975-8b7551a50a1e.png">

2022-11-16 12:22 UTC, hyesungoh requested changes
지금 3개의 폴더, 파일들이 신아님 이름 밖에 위치하고 있어요 ~ 확인 후 지워주세요~

2022-11-16 13:01 UTC, yeeZinu commented on kimsina/src/components/StoreTextingDetail.tsx
> +`;
👍

2022-11-16 13:01 UTC, yeeZinu commented on kimsina/src/components/StoreCircle.tsx
>  export default StoreCircle;
오 사진 둥글게 만드는건 히트네요

2022-11-17 05:37 UTC, hanseulhee approved these changes
`궁금한 점 보다는.. 사과의 말씀 드립니다..저번에 슬희님께서 태그 이름 지을 때 한번 읽어보면 좋을 글 추천해주셨는데 그걸 읽고 했어야 했는데 너무 바빠서 그렇게 하지 못했어요 ㅠㅠ 다음번에는 그렇게 하겠습니다 ㅠㅠ`
좋아요 ~~~ 너무 수고하셨어요 👏🏻👏🏻👏🏻👏🏻

2022-11-17 05:37 UTC, hanseulhee commented on kimsina/src/components/StoreTextingDetail.tsx
> +const StoreTextingDetail = ({ title, address, menu }: Props) => {
👍🏻👍🏻👍🏻👍🏻

2022-11-17 05:37 UTC, hanseulhee commented on kimsina/src/components/Store.tsx
> +    <StoreCss className="Store">
styled-components를 적용하셨는데 className을 따로 하신 이유가 있나요? 지우는 게 좋을 것 같아요 ~

2022-11-17 05:37 UTC, hanseulhee commented on kimsina/src/components/StoreTexting.tsx
> +
StoreTexting는 아직 하고 계신 걸까요??

2022-11-17 05:37 UTC, hanseulhee commented on kimsina/src/components/Store.tsx
> +          menu="마왕통구이"
정말 맛있어 보여요 !!🤩👍🏻

2022-11-17 05:37 UTC, hanseulhee commented on kimsina/src/components/Store.tsx
> +        <StoreCircle src="img/sushi.jpeg" />
img 폴더도 만들어서 정리하셨다니 👍🏻

2022-11-17 06:20 UTC, hyesungoh approved these changes
오호 굿굿 입니다 👍 👍 👍 👍 

컴포넌트 분리 잘 하시는 것 같아요 ~~~ 💯

2022-11-17 06:22 UTC, sinamong0620 commented on kimsina/src/components/StoreTexting.tsx
> +
이게 그 제가 작업하다가 이 파일이 필요가 없어져서 지울려고 했는데 갑자기 지우니까 오류가 나가지고 일단 비워둔 상태로 둔겁니다.. 지우고 했었어야 했는데 막 시간이 없다보니까 부랴부랴 내버렸네요 ㅠㅠㅠ..

2022-11-17 06:42 UTC, merged