GDSC SKHU Web - 이진우
GDSC-SKHU/GDSC-Web-Assignment-03 pull request #2
Opened 2022-11-15 13:13 UTC by yeeZinu

## Description

- Restrorant.tsx 제작
- hover 이미지 확대 시 hidden으로 숨김

## Important content

- hover에 scale로 키운것을 hidden으로 숨김
- 현재 페이지에서 이동하는게 불편해서 새 창에 주소 열림

## Question

- 있었는데요 없었습니다.
- 

## Reference

컬러헌트 -> 배경 및 폰트 색
망고 플레이트 -> 전반적인 스타일

## 과제 실행 사진
![image](https://user-images.githubusercontent.com/33426203/201928317-276d8739-250c-4f60-a62d-1e611ee6d82b.png)

2022-11-15 13:18 UTC, hyesungoh requested changes
본인 영문 이름으로 된 폴더에 넣어주셔야 돼요 ~

2022-11-15 13:18 UTC, hanseulhee approved these changes
👍🏻👍🏻👍🏻 수고하셨어요!

2022-11-15 13:18 UTC, hanseulhee commented on src/App.tsx
> +        />
ㅋㅋㅋㅋㅋ 아비꼬 정말 맛있어요!

2022-11-15 13:18 UTC, hanseulhee commented on src/components/Restorant.tsx
> +const Restrorant = ({title, review, address, imgSrc, mapSrc}: Props) => {
👍🏻👍🏻👍🏻👍🏻

2022-11-15 13:18 UTC, hanseulhee commented on src/components/Restorant.tsx
> +const StyledTle = styled.div`
StyledContentWrapper 과 같은 이름도 좋을 것 같아요!

2022-11-15 13:18 UTC, hanseulhee commented on src/App.tsx
> +          review='우동 원픽!면이 아주 쫄깃함 + 한무 리필 = 미침'
오호 .. 대박이군요

2022-11-15 13:24 UTC, hanseulhee requested changes
😢

2022-11-16 11:51 UTC, yeeZinu commented
파일 다시 수정해서 올렸습니다

2022-11-16 11:58 UTC, hyesungoh requested changes
지금 폴더에 옮겨지지 않은 파일들도 다 옮겨주셔야돼요~

2022-11-16 12:50 UTC, sinamong0620 reviewed
아주아주 멋있는 맛집 소개 페이지입니다. 전체적으로 색이 노래서 약간 아따맘마 쿠킹 클래스를 연상시키는거 같아요! 나중에 여기 맛집도 꼭 가봐야겠어요~~ 잘 보았습니다!

2022-11-16 12:50 UTC, sinamong0620 commented on leejinwoo/src/components/Restorant.tsx
> +            </StyledDiv>
오 저는 진짜 컴포넌트 범벅을 해놨는데 진우님은 깔끔하게 컴포넌트를 많이 하지 않으셨네용.. 괜히 제가 뻘쭘해집니다 하핳..

2022-11-16 12:50 UTC, sinamong0620 commented on leejinwoo/src/components/Restorant.tsx
> +`;
styled-components도 아주 깨끗하게 잘 하신거같아요!! 저도 다음번에는 이렇게 띄어쓰기도 해봐야겠어요~

2022-11-16 13:08 UTC, yeeZinu commented
다시 수정했습니다!

2022-11-16 13:09 UTC, yeeZinu commented on leejinwoo/src/components/Restorant.tsx
> +            </StyledDiv>
저는 오히려 컴포넌트 많이있어서 오 대단하다 생각했어요 ㅋㅋㅋ

2022-11-16 13:44 UTC, hyesungoh requested changes
진우님 지금 `leejinwoo` 폴더 밖에 `node_modules`가 있어요

노드 모듈스는 디펜던시들이 위치한 폴더라 용량이 매우크고 파일 수가 매우 많아요.

그래서 지금 4백만줄이 diff로 걸렸어요 > 이걸 위해서 gitignore가 존재하는겁니다!

---
그리고 지우면 안되는 파일 > root의 .gitignore, 리드미가 지워졌어요~

2022-11-21 07:07 UTC, yeeZinu commented
.gitignore, 리드미 추가했습니다

2022-11-21 08:28 UTC, hyesungoh approved these changes
👍 👍 👍 👍 👍 👍 굿굿 깔끔합니다 ~

전체적으로 코드에 의미없는 줄바꿈, 띄어쓰기 등이 많은 거 같아요

이룰 위해서 포매터를 적극적으로 활용하시는 걸 추천 드립니다~~

2022-11-21 08:28 UTC, hyesungoh commented on leejinwoo/src/App.tsx
> +`;
이런 경우는 그냥 태그를 노출해도 되겠죠 !

2022-11-22 05:29 UTC, hanseulhee approved these changes
수고하셨어요 👍🏻 👍🏻 👍🏻 👍🏻

2022-11-22 05:29 UTC, hanseulhee commented on leejinwoo/src/components/Restorant.tsx
> +const Restrorant = ({title, review, address, imgSrc, mapSrc}: Props) => {
Restaurant을 쓰려고 하신 것 같아요!

과제 가이드라인은 Store.tsx로 나와 있어서 다음번에는 가이드라인 맞춰서 해주시면 좋을 것 같아요 😄

2022-11-22 05:29 UTC, hanseulhee commented on leejinwoo/src/components/Restorant.tsx
> +        <Styledsection>
여기도 StyledSection으로 하는 게 좋을 것 같아요 ~~

2022-11-22 05:29 UTC, hanseulhee commented on leejinwoo/src/components/Restorant.tsx
> +    }
👍🏻👍🏻👍🏻👍🏻

2022-11-22 05:30 UTC, merged