GDSC-WEB-이예슬
GDSC-SKHU/GDSC-Web-Assignment-03 pull request #8
Opened 2022-11-16 05:19 UTC by yeaseul7

## Description

- movie로 구현했던것을 토대로 변화를 주었습니다.
- const를 사용해서 배열안에 number 를 넣어 화면이 바뀔 수 있도록 했습니다.

## Important content

- 제목 밑에 음식 아이콘을 누르면 아이콘 종류별로 그 분야 추천 맛집을 나타내줍니다.
- 맛집 여러곳을 추천했다는 것.

## Question

- 버튼을 눌렀을때마다 number가 달라지게 해서 다른 화면을 구현하도록 했는데 다른 화면마다 중복되는 태그들이 있었습니다.
그부분을 반복되지 않게 코드를 짜고 싶었는데 잘 되지 않았어요..ㅠㅠ

## Reference
https://ko.reactjs.org/docs/hooks-reference.html#usestate
근데 잘 이해를 못했어요.

## 과제 실행 사진
<img width="1440" alt="스크린샷 2022-11-16 오후 2 12 47" src="https://user-images.githubusercontent.com/104067367/202089493-d49904ab-9046-4f20-a328-df107a7f9a21.png">

2022-11-16 11:08 UTC, hyesungoh requested changes
예슬님 지금 폴더 디렉토리가 `이예슬/react/gdscstudy` 안에 있어요 ~

가이드라인 보시면 영문 이름 하위에 두라고 되어있습니다~

2022-11-16 12:37 UTC, zoeyourlife commented on 이예슬/react/gdscstudy/src/components/Nav.tsx
> +        {/* 완전히 이해하면 이렇게 쓸 수 있도록 하기 */}
👍 👍 🔖

2022-11-16 12:37 UTC, zoeyourlife commented on 이예슬/react/gdscstudy/src/components/Restaurant.tsx
> +`;
👍 👍 👍 👍 👍 👍 👍 👍

2022-11-16 12:37 UTC, zoeyourlife commented on 이예슬/react/gdscstudy/src/components/Nav.tsx
> +const Nav = ({ setter }: {setter: React.Dispatch<React.SetStateAction<number>>}) => {
👍 👍 📖

2022-11-16 13:00 UTC, hyesungoh requested changes
지금 폴더 그대로이며, 기존에 있던 (지우면 안되는) 파일들을 지우셨어요~

2022-11-16 13:02 UTC, hyesungoh requested changes
변경 이후에 리뷰 재요청해주세요

2022-11-16 13:17 UTC, yeaseul7 commented
아직도 그대론가요..?

2022-11-16 13:27 UTC, yeaseul7 commented
돌아가는거 누르면 알림가는거였군요...이제 이해했네요...😅😢

2022-11-16 13:39 UTC, hanseulhee commented
@yeaseul7 예슬님 지금 잘 되었는데 과제 가이드라인 보시면 영문 이름으로 리액트 앱을 만들어야 하는 거였어서 yeaseul/react/gdscstudy가 아니라 yeaseul로 되어있어야 해요

그리고 Store.tsx를 사용해달라고 했는데 pr 올려주신 데에서는 안 보이네요 ㅠㅠ

다음 과제부터는 가이드라인 더 지켜주시길 바래요 👍🏻👍🏻

2022-11-16 13:46 UTC, yeaseul7 commented
아 넵 ㅠㅠ 수정 또 했는데 이번에는 잘 됐는지 모르겠네요.. 
다음부턴 가이드 라인 더 자세히 숙지하겠습니다 ㅠㅠ

2022-11-16 14:14 UTC, hyesungoh approved these changes
👍 👍 👍 👍 👍 
열심히 해주셨는데 ㅠㅠ 저도 아쉽네요

다음부터는 확인 부탁드려요!

2022-11-16 14:14 UTC, hyesungoh commented on yeaseul/src/App.tsx
> +//css인 js..? css 안에 js 변수를 넣을 수 있다.
CSS in JS 입니다 ㅋㅋㅋㅋㅋㅋ 👍 👍 👍 👍

2022-11-16 14:14 UTC, hyesungoh commented on yeaseul/src/components/Nav.tsx
> +const Nav = ({ setter }: {setter: React.Dispatch<React.SetStateAction<number>>}) => {
이렇게 인라인 타입 보다는 인터페이스 사용을 권장해요 ~
```suggestion
interface Props {
 setter: Dispatch<SetStateAction<number>>;
}

const Nav = ({ setter }: Props) => {
```

2022-11-16 14:14 UTC, hyesungoh commented on yeaseul/src/components/Store.tsx
> +}
ㅋㅋㅋㅋㅋㅋ 고생하셨습니다 👍 👍 
이런 경우에는 객체를 받으면 더 편할 거 같지 않으세요?

```suggestion

interface Menu {
  src: string;
  name: string;
  price: string;
}

interface Props {
  title: string;
  summary: string;
  imgSrc: string;
  grade: string;
  grade2: string;
  menu1: Menu;
  menu2: Menu;
  menu3: Menu;
}
```

혹은 여기서 더 나가서 배열로도 받을 수 있겠구요 ~

```
menus: Menu[];
```

반복되는 작업을 어떻게 줄이면서 직관적으로 풀어나갈지 고민해 보시면 좋을 거 같아요!

2022-11-16 16:20 UTC, hanseulhee approved these changes
정말 수고하셨어요 👏🏻👏🏻👏🏻👏🏻👏🏻

맛tamnang은 무슨 뜻인가요?? 🤔

2022-11-16 16:20 UTC, hanseulhee commented on yeaseul/src/components/Store.tsx
> +  font-family: serif;
globalStyle을 이용해 font-family를 적용해보시면 좋을 것 같아요 ~

2022-11-16 16:20 UTC, hanseulhee commented on yeaseul/src/App.tsx
> +          price2="9,900원"
허걱 진짜 맛있어 보여요 !!🤭

2022-11-16 16:20 UTC, hanseulhee commented on yeaseul/src/components/Store.tsx
> +  return (
예슬님의 열정이 느껴집니다 👍🏻👍🏻👍🏻👍🏻
혜성님이 말씀하신 내용 참고해주시면 좋을 것 같아요!

2022-11-16 16:20 UTC, hanseulhee commented on yeaseul/src/components/Store.tsx
> +const StyledArticle = styled.article`
👍🏻👍🏻👍🏻👍🏻

2022-11-16 16:20 UTC, hanseulhee commented on yeaseul/src/App.tsx
> +
벌써 useState도 하셨다니 👍🏻👍🏻👍🏻

2022-11-17 02:28 UTC, merged

2022-11-17 02:56 UTC, yeaseul7 commented on yeaseul/src/App.tsx
> +//css인 js..? css 안에 js 변수를 넣을 수 있다.
앗 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ🫢

2022-11-17 02:57 UTC, yeaseul7 commented on yeaseul/src/components/Nav.tsx
> +const Nav = ({ setter }: {setter: React.Dispatch<React.SetStateAction<number>>}) => {
😮오..넵!

2022-11-17 02:59 UTC, yeaseul7 commented on yeaseul/src/components/Store.tsx
> +}
오.... 이런 방법이...🫢

2022-11-17 03:00 UTC, yeaseul7 commented on yeaseul/src/App.tsx
> +          price2="9,900원"
진짜 최고 맛있어요 ㅎㅎㅎ

2022-11-17 03:00 UTC, yeaseul7 commented on yeaseul/src/components/Store.tsx
> +  return (
ㅋㅋㅋㅋㅋㅋㅋㅋ 반복 작업 수정하는거 고민해도 답이 쉽게 안나오네욤...감사합니다!!!

2022-11-17 03:00 UTC, yeaseul7 commented on yeaseul/src/App.tsx
> +
잘 모르는데 사용해 봤어요...ㅎㅎㅎ

2022-11-17 03:00 UTC, yeaseul7 commented on yeaseul/src/components/Store.tsx
> +  font-family: serif;
넵 :)

2022-11-17 03:01 UTC, yeaseul7 commented
맛 탐 방 + 탐난다 => 맛탐낭 입니다 ㅋㅋㅋㅋㅋㅋㅋㅋ